//! Embed the library's DATA into the binary (plan WP5, decision 10): the vendored SLEIGH processor
//! tree (`.ldefs`/`.sla`/`.pspec`/`.cspec`/`.opinion` and the pattern files), mosura's own compiler
//! specs and pattern files (`specs/`), and mosura's own FID databases (`data/fid/*.mfid.gz`).
//! Ghidra's vendored FID databases (`third_party/ghidra-data/FunctionID`, ~76 MB) are embedded
//! only under the `fid-ghidra` feature; in the workspace they are reached as an override instead.
//!
//! Writes `$OUT_DIR/embedded.rs`: `pub static EMBEDDED: &[(&str, &[u8])]`, one entry per file,
//! named by its resource path — `ghidra/Processors/<P>/data/languages/<f>`,
//! `ghidra/Processors/<P>/data/patterns/<f>`, `specs/<f>`, `specs/patterns/<f>`, `fid/<f>` —
//! sorted, so the table is deterministic. `crate::resources` reads it.
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let ws = manifest.ancestors().nth(2).expect("workspace root").to_path_buf();
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded.rs");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    let procs = ws.join("third_party/ghidra/Processors");
    walk(&procs, &mut |p| {
        let ext = p.extension().and_then(|e| e.to_str()).unwrap_or("");
        let in_langs = p.parent().is_some_and(|d| d.ends_with("data/languages"));
        let in_patterns = p.parent().is_some_and(|d| d.ends_with("data/patterns"));
        if (in_langs && matches!(ext, "ldefs" | "sla" | "pspec" | "cspec" | "opinion")) || in_patterns {
            let rel = p.strip_prefix(&procs).unwrap();
            entries.push((format!("ghidra/Processors/{}", slashed(rel)), p.to_path_buf()));
        }
    });
    let specs = ws.join("specs");
    walk(&specs, &mut |p| {
        if p.extension().and_then(|e| e.to_str()) != Some("md") {
            entries.push((format!("specs/{}", slashed(p.strip_prefix(&specs).unwrap())), p.to_path_buf()));
        }
    });
    let fid = ws.join("data/fid");
    walk(&fid, &mut |p| {
        let n = p.file_name().unwrap().to_string_lossy();
        if n.ends_with(".mfid.gz") || n.ends_with(".mfid") {
            entries.push((format!("fid/{n}"), p.to_path_buf()));
        }
    });
    if std::env::var_os("CARGO_FEATURE_FID_GHIDRA").is_some() {
        let g = ws.join("third_party/ghidra-data/FunctionID");
        walk(&g, &mut |p| {
            let n = p.file_name().unwrap().to_string_lossy();
            if n.ends_with(".fidb") {
                entries.push((format!("fid/{n}"), p.to_path_buf()));
            }
        });
    }
    entries.sort();
    entries.dedup_by(|a, b| a.0 == b.0);

    let mut src = String::from("/// Generated by build.rs — the embedded resources, sorted by name.\npub static EMBEDDED: &[(&str, &[u8])] = &[\n");
    let mut total = 0u64;
    for (name, path) in &entries {
        total += std::fs::metadata(path).map(|m| m.len()).unwrap_or(0);
        src.push_str(&format!("    ({name:?}, include_bytes!({:?})),\n", path.display().to_string()));
    }
    src.push_str("];\n");
    src.push_str(&format!("/// Bytes embedded, for the record.\npub const EMBEDDED_BYTES: u64 = {total};\n"));
    std::fs::write(&out, src).expect("write embedded.rs");
    for d in [&procs, &specs, &fid] {
        println!("cargo:rerun-if-changed={}", d.display());
    }
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:warning=mosura: embedded {} resource files, {:.1} MB", entries.len(), total as f64 / 1e6);
}

fn slashed(rel: &Path) -> String {
    rel.components().map(|c| c.as_os_str().to_string_lossy().into_owned()).collect::<Vec<_>>().join("/")
}

fn walk(dir: &Path, f: &mut dyn FnMut(&Path)) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    let mut paths: Vec<PathBuf> = rd.flatten().map(|e| e.path()).collect();
    paths.sort();
    for p in paths {
        if p.is_dir() {
            walk(&p, f);
        } else if p.is_file() {
            f(&p);
        }
    }
}
