//! The committed header and the crate agree: every `extern "C"` function of `mosura-capi` is
//! declared in `include/mosura.h`, and every `mosura_*` function the header declares exists in
//! the crate. Pins header drift without cbindgen in the test build (design E11: the header is
//! regenerated by `cargo xtask header` and reviewed like source).

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).ancestors().nth(2).expect("workspace root").to_path_buf()
}

/// The `mosura_*` functions the crate exports (`#[no_mangle] pub [unsafe] extern "C" fn NAME`).
fn crate_functions() -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let src = workspace_root().join("crates/mosura-capi/src");
    let mut stack = vec![src];
    while let Some(d) = stack.pop() {
        for e in std::fs::read_dir(&d).unwrap().flatten() {
            let p = e.path();
            if p.is_dir() {
                stack.push(p);
                continue;
            }
            if p.extension().is_none_or(|x| x != "rs") {
                continue;
            }
            let text = std::fs::read_to_string(&p).unwrap();
            let lines: Vec<&str> = text.lines().collect();
            for (i, line) in lines.iter().enumerate() {
                if line.trim() != "#[no_mangle]" {
                    continue;
                }
                let decl = lines.get(i + 1).copied().unwrap_or("");
                let Some(rest) = decl.trim_start().strip_prefix("pub ") else { continue };
                let rest = rest.strip_prefix("unsafe ").unwrap_or(rest);
                let Some(rest) = rest.strip_prefix("extern \"C\" fn ") else { continue };
                // no macro-generated exports: cbindgen reads the source, not expansions
                assert!(!rest.starts_with('$'), "{}: an exported function generated by a macro is invisible to cbindgen", p.display());
                let name: String = rest.chars().take_while(|c| c.is_ascii_alphanumeric() || *c == '_').collect();
                assert!(name.starts_with("mosura_"), "{}: exported function `{name}` is not mosura_-prefixed", p.display());
                out.insert(name);
            }
        }
    }
    out
}

/// The functions the header declares: on a declaration line (not a comment, a directive or a
/// typedef), every `mosura_<name>(` token.
fn header_functions(header: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut in_comment = false;
    for line in header.lines() {
        let t = line.trim();
        if in_comment {
            if t.contains("*/") {
                in_comment = false;
            }
            continue;
        }
        if t.starts_with("/*") {
            if !t.contains("*/") {
                in_comment = true;
            }
            continue;
        }
        if t.starts_with('#') || t.starts_with("typedef") || t.is_empty() || t.starts_with("extern \"C\"") {
            continue;
        }
        let mut rest = t;
        while let Some(pos) = rest.find("mosura_") {
            let after = &rest[pos..];
            let name: String = after.chars().take_while(|c| c.is_ascii_alphanumeric() || *c == '_').collect();
            if after[name.len()..].starts_with('(') {
                out.insert(name.clone());
            }
            rest = &after[name.len()..];
        }
    }
    out
}

#[test]
fn the_header_declares_exactly_the_crates_functions() {
    let header = std::fs::read_to_string(workspace_root().join("include/mosura.h")).expect("include/mosura.h is committed (cargo xtask header)");
    let declared = header_functions(&header);
    let exported = crate_functions();
    assert!(exported.len() >= 60, "{} exported functions found", exported.len());
    let missing: Vec<&String> = exported.difference(&declared).collect();
    let extra: Vec<&String> = declared.difference(&exported).collect();
    assert!(missing.is_empty() && extra.is_empty(), "header drift — regenerate with `cargo run -p xtask --features header -- header`.\n  exported but not declared: {missing:?}\n  declared but not exported: {extra:?}");
    // the shapes the design fixes: opaque handles, size/version struct, the initializer macro
    for needle in ["typedef struct mosura_ctx mosura_ctx;", "typedef struct mosura_table mosura_table;", "uint32_t size;", "uint32_t version;", "#define MOSURA_CTX_CONFIG_INIT", "#define MOSURA_API_VERSION_MAJOR 0", "typedef void (*mosura_log_fn)", "typedef int (*mosura_progress_fn)", "void mosura_release(void *h);"] {
        assert!(header.contains(needle), "header lacks `{needle}`");
    }
}
