#!/usr/bin/env python3
"""Build the 68000 emulation oracle ROMs and record BlastEm's results (tests/emu_m68k.rs).

    VASM=vasmm68k_mot BLASTDBG=blastdbg BDTRACE_DIR=<dir of bdtrace.py> \
        generate.py fixtures   # the committed set, into this directory
        generate.py all OUT    # every variant, into OUT/roms and OUT/ram (dev-config oracle.m68k_emulation)

Each ROM writes $DEAD to $FFFF00 when it is done; the result is BlastEm's work RAM in the first
trace record where that marker is set. `div.s` is generated here: its 4000 dividend/divisor
pairs are fixed edges plus a seeded random draw, so every run builds the same ROM. The shift and
rotate ROMs are generated by shifts.py.
"""
import os, random, subprocess, sys, tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
VASM = os.environ.get("VASM", "vasmm68k_mot")
BLASTDBG = os.environ.get("BLASTDBG", "blastdbg")
sys.path.insert(0, os.environ.get("BDTRACE_DIR", "."))


def div_source():
    random.seed(68000)
    edges32 = [0, 1, 2, 0x7fff, 0x8000, 0xffff, 0x10000, 0x7fff0000, 0x7fffffff, 0x80000000, 0x80000001,
               0xffffffff, 0xfffffffe, 0xffff8000, 0x00008000, 0x0001ffff, 0xfffe0000, 0x3fff8000, 0xc0008000,
               0x12345678, 0xff0101]
    edges16 = [1, 2, 3, 0x7fff, 0x8000, 0x8001, 0xffff, 0xfffe, 0x10, 0x100, 0x1234]
    pairs = [(a, b) for a in edges32 for b in edges16]
    while len(pairs) < 4000:
        a = random.getrandbits(32); b = random.getrandbits(16) or 1
        k = random.random()
        if k < 0.3: a = random.getrandbits(random.randint(1, 32))
        if k > 0.7: b = random.getrandbits(random.randint(1, 16)) or 1
        if random.random() < 0.2: a = a ^ 0xffffffff
        pairs.append((a, b))
    head = """	org 0
	dc.l $00FFFE00, start
	dcb.l 62, start
	org $100
	dc.b "SEGA MEGA DRIVE "
	dcb.b $100-16, $20
start:
	move.w #$2700,sr
	lea $FF0000,a2
	lea table,a3
	move.w #%d-1,d7
loop:
	move.l (a3)+,d0
	move.w (a3)+,d1
	move #CCRIN,ccr
	if SIGNED
	divs.w d1,d0
	else
	divu.w d1,d0
	endif
	move sr,d2
	move.l d0,(a2)+
	move.w d2,(a2)+
	dbra d7,loop
	move.w #$DEAD,$FFFF00
done:
	bra done
table:
""" % len(pairs)
    return head + "".join("\tdc.l $%08x\n\tdc.w $%04x\n" % p for p in pairs)


def build(source, defines, rom):
    if isinstance(source, str):
        path = Path(tempfile.mkdtemp()) / "rom.s"
        path.write_text(source)
        source = path
    args = [VASM, "-quiet", "-Fbin", "-m68000", "-o", str(rom)] + ["-D%s=%d" % kv for kv in defines.items()]
    subprocess.run(args + [str(source)], check=True, stdout=subprocess.DEVNULL)


def blastem_ram(rom):
    from bdtrace import Trace
    data = rom.read_bytes()
    with tempfile.TemporaryDirectory() as tmp:
        padded, trace = Path(tmp) / "rom.bin", Path(tmp) / "run.trc"
        padded.write_bytes(data + bytes(-len(data) % 0x2000))
        subprocess.run([BLASTDBG, "--trace", str(trace), "--frames", "0-60", str(padded)], check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        with Trace(str(trace)) as t:
            for rec in t:
                if rec.ram[0xFF00:0xFF02] == b"\xde\xad":
                    return bytes(rec.ram)
    sys.exit("%s never finished" % rom)


def variants(everything):
    bcd = [(op, ccr, x0) for op in range(6) for ccr in (0, 4, 16, 20) for x0 in (0, 64, 128, 192)]
    if not everything:
        bcd = [(0, 20, 128), (1, 20, 128), (2, 20, 128), (2, 4, 0), (3, 0, 64), (4, 0, 64), (5, 20, 128)]
    for op, ccr, x0 in bcd:
        yield "bcd-%d-%d-%d" % (op, ccr, x0), "bcd.s", dict(OPK=op, CCRIN=ccr, X0=x0), 2 * 64 * 256
    for signed in (0, 1):
        for ccr in ((0, 31) if everything else (31,)):
            yield "div-%d-%d" % (signed, ccr), "div.s", dict(SIGNED=signed, CCRIN=ccr), 6 * 4000
    yield "forms", "forms.s", {}, 30
    yield "nbcd-memory", "nbcd-memory.s", {}, 0x14
    sys.path.insert(0, str(HERE))
    import shifts
    for name, (source, cases) in shifts.variants(everything):
        yield name, source, {}, 6 * cases


def main():
    everything = sys.argv[1:2] == ["all"]
    out = Path(sys.argv[2]) if everything else HERE
    roms, rams = (out / "roms", out / "ram") if everything else (out, out)
    roms.mkdir(parents=True, exist_ok=True); rams.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        div = Path(tmp) / "div.s"
        div.write_text(div_source())
        for name, source, defines, used in variants(everything):
            rom = roms / (name + ".bin")
            if source == "div.s":
                source = div
            elif source.endswith(".s"):
                source = HERE / source
            build(source, defines, rom)
            ram = blastem_ram(rom)
            (rams / (name + ".ram")).write_bytes(ram if everything else ram[:used])


if __name__ == "__main__":
    main()
