/*
 * mosura.h — the mosura C API, FIRST DRAFT (2026-09-05).
 *
 * This header is the shape of the surface, written before the implementation so that the shape
 * can be discussed. It will be GENERATED by cbindgen from `mosura-capi` once that crate exists;
 * until then it is hand-written and syntax-checked only.
 *
 * Reading order: §1 conventions, §2 handles, §3 context, §4 options, §5 tables, §6 operations
 * (the generic spine), §7–§11 the typed entry points, layer by layer. The design behind it is
 * `docs/product/architecture.md`.
 *
 * Conventions (architecture.md §4.5):
 *   - Every function returns a `mosura_status`; details via `mosura_last_error()` (thread-local).
 *   - No panic crosses this boundary: an internal failure is `MOSURA_ERR_INTERNAL` + message.
 *   - Handles are opaque; every handle type is released with `mosura_release()`.
 *   - `mosura_view`  = borrowed bytes, valid while the handle that produced it lives (tables are
 *                      immutable, so a view into a table is stable for the table's lifetime).
 *   - `mosura_bytes` = owned bytes, freed with `mosura_bytes_dispose()`.
 *   - Strings are UTF-8 with explicit lengths; `const char*` parameters are NUL-terminated.
 *   - Structs passed by pointer start with `size` + `version`; use the `_INIT` macros.
 *   - Nothing here reads the environment or assumes a filesystem; `mosura_session_open(NULL)`
 *     is an in-memory session (the wasm case).
 */
#ifndef MOSURA_H
#define MOSURA_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §1  Version, status, memory                                                                 */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

#define MOSURA_API_VERSION_MAJOR 0
#define MOSURA_API_VERSION_MINOR 1

/** Runtime ABI version, `(major << 16) | minor`. A client checks the major before anything else. */
uint32_t mosura_abi_version(void);
/** Human version string, e.g. "0.1.0+g2ee9459" (the build id that also keys the session store). */
const char *mosura_version(void);

typedef enum mosura_status {
    MOSURA_OK = 0,
    MOSURA_ERR_INVALID_ARG,   /* NULL where a value is required, bad option key/value, bad handle kind */
    MOSURA_ERR_NOT_FOUND,     /* no such function / table / operation / cache entry */
    MOSURA_ERR_IO,            /* session directory, input file, toolchain work dir */
    MOSURA_ERR_FORMAT,        /* unreadable input, corrupt .tbl, unknown schema version */
    MOSURA_ERR_UNSUPPORTED,   /* no loader claims the file, language has no tables, op not built in */
    MOSURA_ERR_TOOLCHAIN,     /* the compiler could not be run (not: the source failed to compile) */
    MOSURA_ERR_CANCELLED,     /* a progress callback returned non-zero */
    MOSURA_ERR_VERSION,       /* struct size/version mismatch, or a session written by an incompatible build */
    MOSURA_ERR_INTERNAL       /* a panic was caught at the boundary; message = the panic text */
} mosura_status;

/** The message for the last non-OK status on THIS thread. Valid until the next mosura call on
 *  the thread. Never NULL (empty string when there is none). */
const char *mosura_last_error(void);

/** Borrowed, immutable bytes. Lifetime = the handle documented at the producing function. */
typedef struct mosura_view {
    const uint8_t *ptr;
    size_t len;
} mosura_view;

/** Owned bytes. Dispose exactly once. Zero-initialized is a valid empty value. */
typedef struct mosura_bytes {
    uint8_t *ptr;
    size_t len;
    size_t cap;
} mosura_bytes;
void mosura_bytes_dispose(mosura_bytes *b);

/** Release any handle (`mosura_ctx*`, `mosura_session*`, …). NULL is a no-op. A handle must
 *  outlive every handle derived from it (a program outlives its functions; a ctx outlives all). */
void mosura_release(void *handle);

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §2  Handles (opaque)                                                                        */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

typedef struct mosura_ctx mosura_ctx;               /* the library: spec registry, caches, log sink */
typedef struct mosura_options mosura_options;       /* validated key/value option set */
typedef struct mosura_table mosura_table;           /* an immutable result table with a schema */
typedef struct mosura_session mosura_session;       /* a session store (directory or memory) */
typedef struct mosura_language mosura_language;     /* a SLEIGH language: tables + default context */
typedef struct mosura_program mosura_program;       /* a loaded (and possibly analyzed) binary */
typedef struct mosura_function mosura_function;     /* one decompiled function (results + the live graph) */
typedef struct mosura_toolchain mosura_toolchain;   /* a compiler mosura can drive, with its cache */

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §3  Context                                                                                 */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

typedef enum mosura_log_level { MOSURA_LOG_ERROR = 0, MOSURA_LOG_WARN, MOSURA_LOG_INFO, MOSURA_LOG_DEBUG } mosura_log_level;

/** Diagnostic sink. `topic` is the debug topic (`sparse-switch`, `analysis`, …) or "" for
 *  untopiced messages. Replaces every stderr print in the library. */
typedef void (*mosura_log_fn)(void *user, mosura_log_level level, const char *topic, const char *msg, size_t msg_len);

/** Progress callback for long operations (analysis, rounds). Return non-zero to cancel; the
 *  operation then fails with MOSURA_ERR_CANCELLED and leaves no partial state in the session. */
typedef int (*mosura_progress_fn)(void *user, const char *stage, uint64_t done, uint64_t total);

typedef struct mosura_ctx_config {
    uint32_t size;                    /* sizeof(mosura_ctx_config) */
    uint32_t version;                 /* 1 */
    /** Directories searched for spec data (`.ldefs`/`.sla`/`.pspec`/`.cspec`) BEFORE the embedded
     *  vendored set. Our own `specs/` is embedded too; this is the user's override folder. */
    const char *const *spec_dirs;
    size_t spec_dirs_len;
    /** Directories searched for FID databases (`.mfid[.gz]`, `.fidb`) before the embedded ones. */
    const char *const *fid_dirs;
    size_t fid_dirs_len;
    /** Machine-level cache for frozen specs etc. NULL = none (in-memory only). */
    const char *cache_dir;
    mosura_log_fn log;
    void *log_user;
} mosura_ctx_config;
#define MOSURA_CTX_CONFIG_INIT { (uint32_t)sizeof(mosura_ctx_config), 1, NULL, 0, NULL, 0, NULL, NULL, NULL }

/** Create the library context. Thread-safe once created; everything derived from it is not,
 *  unless stated. */
mosura_status mosura_ctx_new(const mosura_ctx_config *config, mosura_ctx **out);

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §4  Options — the ONLY way a knob reaches the library (architecture.md §4.2)                */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

mosura_status mosura_options_new(mosura_ctx *ctx, mosura_options **out);
mosura_status mosura_options_clone(const mosura_options *src, mosura_options **out);
/** Set a key. Unknown keys and ill-typed values are MOSURA_ERR_INVALID_ARG with the registry's
 *  doc line in the error message. Keys are dotted lower-case: "load.loader", "analysis.disable",
 *  "emit.return-width", "debug.topics", "toolchain.watcom-10.0a-dos.install". */
mosura_status mosura_options_set(mosura_options *o, const char *key, const char *value);
mosura_status mosura_options_unset(mosura_options *o, const char *key);
/** The effective value (explicit or default). View valid until the next mutation of `o`. */
mosura_status mosura_options_get(const mosura_options *o, const char *key, mosura_view *out);
/** Canonical string of the RESULT-affecting subset — the option digest used in cache keys. */
mosura_status mosura_options_tag(const mosura_options *o, mosura_bytes *out);
/** Parse "key=value;key=value" (the `EmitChoices::assign` grammar, generalized). */
mosura_status mosura_options_assign(mosura_options *o, const char *spec);
/** The registry: one row per key — key, type, default, doc, since, affects(result|diagnostic|environment). */
mosura_status mosura_options_registry(mosura_ctx *ctx, mosura_table **out);

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §5  Tables — every result (architecture.md §4.3)                                             */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

typedef enum mosura_col_type {
    MOSURA_COL_U8 = 1, MOSURA_COL_U16, MOSURA_COL_U32, MOSURA_COL_U64,
    MOSURA_COL_I64, MOSURA_COL_F64, MOSURA_COL_BOOL,
    MOSURA_COL_STR,        /* UTF-8, in the blob */
    MOSURA_COL_BYTES,      /* raw bytes, in the blob */
    MOSURA_COL_LIST_U32,   /* variable-length list, in the blob */
    MOSURA_COL_LIST_U64
} mosura_col_type;

typedef enum mosura_format { MOSURA_FMT_TEXT = 0, MOSURA_FMT_TSV, MOSURA_FMT_JSON } mosura_format;

/** Schema identity: name (e.g. "functions"), version, column count. */
mosura_status mosura_table_schema(const mosura_table *t, mosura_view *name, uint32_t *version, uint32_t *ncols);
mosura_status mosura_table_column_info(const mosura_table *t, uint32_t col, mosura_view *name, mosura_col_type *type);
/** Column index by name, or MOSURA_ERR_NOT_FOUND — the way a client survives appended columns. */
mosura_status mosura_table_column_index(const mosura_table *t, const char *name, uint32_t *col);
uint64_t mosura_table_rows(const mosura_table *t);

/* Cell accessors. Type mismatch is MOSURA_ERR_INVALID_ARG. Views are valid for the table's life. */
mosura_status mosura_table_u64(const mosura_table *t, uint64_t row, uint32_t col, uint64_t *out);
mosura_status mosura_table_i64(const mosura_table *t, uint64_t row, uint32_t col, int64_t *out);
mosura_status mosura_table_f64(const mosura_table *t, uint64_t row, uint32_t col, double *out);
mosura_status mosura_table_bool(const mosura_table *t, uint64_t row, uint32_t col, int *out);
mosura_status mosura_table_str(const mosura_table *t, uint64_t row, uint32_t col, mosura_view *out);
mosura_status mosura_table_bytes(const mosura_table *t, uint64_t row, uint32_t col, mosura_view *out);
/** A list cell as a view over `count` little-endian elements of the column's element width. */
mosura_status mosura_table_list(const mosura_table *t, uint64_t row, uint32_t col, mosura_view *out, uint64_t *count);

/** Bulk, zero-copy access to a fixed-width column: `out` spans all rows, `stride` is the row
 *  size in bytes (columns are stored row-major; a client builds a strided array view). */
mosura_status mosura_table_column(const mosura_table *t, uint32_t col, mosura_view *out, uint32_t *stride);
/** Binary search on a sorted key column (the table's flag says whether column 0 is sorted). */
mosura_status mosura_table_find(const mosura_table *t, uint32_t col, uint64_t key, uint64_t *row);

/** Render the whole table. TEXT is the human form (for program tables, the Snapshot v1 golden
 *  format); TSV has a header row; JSON is an array of objects. */
mosura_status mosura_table_render(const mosura_table *t, mosura_format format, mosura_bytes *out);
/** The flat `.tbl` image (architecture.md §5.3) — what the session store writes. */
mosura_status mosura_table_serialize(const mosura_table *t, mosura_bytes *out);
/** Open a `.tbl` image (zero-copy when `bytes` outlives the table; the table copies otherwise —
 *  `borrow` says which). */
mosura_status mosura_table_open(mosura_ctx *ctx, mosura_view bytes, int borrow, mosura_table **out);

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §6  Operations — the generic spine (architecture.md §4.1)                                   */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

/** The operation registry as a table: name, doc, since, tier(product|dev), params(schema),
 *  result(schema), cache(pure|effect). Everything reachable below is also reachable here. */
mosura_status mosura_ops(mosura_ctx *ctx, int include_dev, mosura_table **out);
/** The schema of a named table type, as a table of columns. */
mosura_status mosura_schema(mosura_ctx *ctx, const char *table_name, mosura_table **out);
/** Invoke any operation by name. `params` carries the op's parameters as option keys
 *  ("input", "entry", "round", … are ordinary keys). The result is a table; text results are a
 *  one-row table with a `text` column. Pure ops are served from the session store when cached. */
mosura_status mosura_call(mosura_session *s, const char *op, const mosura_options *params,
                          mosura_progress_fn progress, void *progress_user, mosura_table **out);

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §7  Session store (architecture.md §5)                                                     */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

/** Open or create a session. `dir == NULL` is an in-memory session (nothing persists). The
 *  session's own config table supplies option defaults for every operation run in it. */
mosura_status mosura_session_open(mosura_ctx *ctx, const char *dir, const mosura_options *config, mosura_session **out);
/** Add an input binary (content-addressed). `label` is a human name ("war2"); the digest is
 *  what keys everything derived from it. Re-adding identical bytes is a no-op returning the digest. */
mosura_status mosura_session_add_input(mosura_session *s, mosura_view bytes, const char *label, mosura_bytes *digest_hex);
/** inputs: label, digest, size, added. */
mosura_status mosura_session_inputs(mosura_session *s, mosura_table **out);
/** Provenance of a cached table set: inputs, options, build id (`mosura cache explain`). */
mosura_status mosura_session_explain(mosura_session *s, const char *key, mosura_table **out);
/** Drop table sets unreachable from any round or the current config. Reports what it removed. */
mosura_status mosura_session_gc(mosura_session *s, int dry_run, mosura_table **out);

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §8  Languages and the SLEIGH engine                                                         */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

/** languages: id, processor, endian, size, variant, description, cspecs(list of ids). */
mosura_status mosura_languages(mosura_ctx *ctx, mosura_table **out);
/** Load a language by Ghidra id ("x86:LE:32:default"). Served from the frozen-spec cache. */
mosura_status mosura_language_open(mosura_ctx *ctx, const char *language_id, mosura_language **out);
/** registers: name, space, offset, size. */
mosura_status mosura_language_registers(mosura_language *l, mosura_table **out);
/** Disassemble raw bytes. `ctx_regs` sets context registers ("addrsize=1;opsize=1" — the
 *  `.pspec` defaults apply when NULL). instructions: addr, len, bytes, mnemonic, operands, flow. */
mosura_status mosura_disassemble(mosura_language *l, mosura_view bytes, uint64_t base,
                                 const mosura_options *ctx_regs, mosura_table **out);
/** Lift raw bytes to raw p-code. pcode: addr, seq, opcode, output(space,offset,size), inputs(list). */
mosura_status mosura_lift(mosura_language *l, mosura_view bytes, uint64_t base,
                          const mosura_options *ctx_regs, mosura_table **out);
/** Execute the p-code of a byte range with initial register/memory values given as options
 *  ("reg.EAX=0x10;mem.0x1000=..."). state: space, offset, size, value — the final machine state. */
mosura_status mosura_emulate(mosura_language *l, mosura_view bytes, uint64_t base,
                             const mosura_options *initial_state, mosura_table **out);
/** FID fingerprints for a byte range (the Ghidra-identical hash quads). */
mosura_status mosura_fingerprint(mosura_language *l, mosura_view bytes, uint64_t base, mosura_table **out);

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §9  Identify, load, analyze — the Program                                                  */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

/** Everything mosura can say about a file without analysing it (the `identify` example):
 *  container, which loader claims it, native (beyond-Ghidra) loader if any, compiler evidence,
 *  resolved language and cspec, FID databases that apply. One row per fact: key, value, evidence. */
mosura_status mosura_identify(mosura_ctx *ctx, mosura_view bytes, mosura_table **out);

/** Load an input of the session into a Program. `load_opts`: "load.loader=default|native|le",
 *  "load.language=…", "load.cspec=…" (declared instead of detected). Cached by key. */
mosura_status mosura_program_open(mosura_session *s, const char *input, const mosura_options *load_opts, mosura_program **out);
/** Run auto-analysis to convergence. `opts`: "analysis.disable=a,b" and the pass switches.
 *  Cached by key; a cached program returns immediately. */
mosura_status mosura_program_analyze(mosura_program *p, const mosura_options *opts,
                                     mosura_progress_fn progress, void *progress_user);
/** Whole-program passes that feed emission (the survey's pass 1 and marks, promoted):
 *  prototype recovery, tail-return marks, parameter-order evidence, global widths. */
mosura_status mosura_program_passes(mosura_program *p, const mosura_options *opts,
                                    mosura_progress_fn progress, void *progress_user);

/** A program table by name — "blocks", "functions", "bodies", "symbols", "references",
 *  "listing", "relocations", "entry_points", "comments", "compiler", "fid", "foreign",
 *  "protos", "proto_slots", "facts", "annotations". Unknown name: MOSURA_ERR_NOT_FOUND. */
mosura_status mosura_program_table(mosura_program *p, const char *name, mosura_table **out);
/** Bytes of the loaded image. `out` views the program's memory (valid while `p` lives).
 *  Uninitialized ranges are MOSURA_ERR_NOT_FOUND. */
mosura_status mosura_program_read(mosura_program *p, uint64_t addr, size_t len, mosura_view *out);
/** Disassembly of a range from the listing (decoded on demand; text is never stored). */
mosura_status mosura_program_disassemble(mosura_program *p, uint64_t addr, size_t len, mosura_table **out);
/** The session's stable key for this program (the directory under program/). */
mosura_status mosura_program_key(mosura_program *p, mosura_bytes *key_hex);

/** User inputs, kept apart from derived facts because they enter cache keys:
 *  kind = "name" | "prototype" | "noreturn" | "cspec" | "foreign" | "flags" | "comment" | …
 *  Annotations that affect analysis (function starts, noreturn) re-key the program; the rest
 *  re-key only the functions they touch. */
mosura_status mosura_program_annotate(mosura_program *p, const char *kind, uint64_t addr, const char *payload);
mosura_status mosura_program_unannotate(mosura_program *p, const char *kind, uint64_t addr);

/** The Snapshot v1 text (the analysis golden format) — `render(TEXT)` of the program tables. */
mosura_status mosura_program_snapshot(mosura_program *p, mosura_bytes *out);

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §10 Decompile and emit — one function                                                      */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

/** Decompile the function at `entry`. `opts`: "decompile.stage=<name>" to stop after a pipeline
 *  stage (the per-stage IR oracle), "decompile.trace=1" to record rule firings, and any "emit.*"
 *  choices for the default rendering. Cached by key; the live graph is rebuilt on a cache hit
 *  only if a later call needs it. */
mosura_status mosura_function_decompile(mosura_program *p, uint64_t entry, const mosura_options *opts, mosura_function **out);

/** The C rendering under the reference choices (Ghidra's behaviour). */
mosura_status mosura_function_c(mosura_function *f, mosura_bytes *out);
/** The C rendering under explicit emit choices — the θ render (`print_c_with`). */
mosura_status mosura_function_render(mosura_function *f, const mosura_options *emit_choices, mosura_bytes *out);
/** The IR: `stage` = "pre" (lifted p-code before any action), "post" (after the pipeline),
 *  or a pipeline stage name; `format` TEXT = Ghidra `printRaw` form, JSON = structured. */
mosura_status mosura_function_ir(mosura_function *f, const char *stage, mosura_format format, mosura_bytes *out);
/** A function table by name — "prototype", "locals", "globals", "calls", "jumptables",
 *  "blocks", "varnodes", "ops", "structure", "trace", "report", "recovered". */
mosura_status mosura_function_table(mosura_function *f, const char *name, mosura_table **out);

/** The standalone translation unit for a toolchain: prelude + synthesized declarations
 *  (globals, extern prototypes, pragmas) + the body. `opts`: "tu.toolchain=<name>" selects the
 *  prelude and contract vocabulary; "emit.*" and "arms.off=a,b" as for render. */
mosura_status mosura_function_tu(mosura_function *f, const mosura_options *opts, mosura_bytes *out);
/** The witness pass: recover the per-site emit decisions from the ORIGINAL's instructions
 *  (report pass → byte witnesses → second round). Returns the `recovered` table; the function
 *  remembers it for a subsequent `mosura_function_tu`. */
mosura_status mosura_function_recover(mosura_function *f, const mosura_options *opts, mosura_table **out);

/** The emit axes (`EmitChoices::axes`): name, values, default, doc, probe. */
mosura_status mosura_emit_axes(mosura_ctx *ctx, mosura_table **out);
/** The emit arms (`Recovered::ARMS`): name, witness, fixture, switchable. */
mosura_status mosura_emit_arms(mosura_ctx *ctx, mosura_table **out);

/* ────────────────────────────────────────────────────────────────────────────────────────── */
/* §11 Recompile — toolchains, verification, rounds                                           */
/* ────────────────────────────────────────────────────────────────────────────────────────── */

/** The compiler specs known to the library (data, not code): name, host(dos|native),
 *  object_format, flags_grammar, doc. */
mosura_status mosura_toolchain_specs(mosura_ctx *ctx, mosura_table **out);
/** Open a toolchain in this session. `opts`: "toolchain.spec=watcom-10.0a-dos",
 *  "toolchain.install=<dir>" (machine config normally supplies it), "toolchain.role=validation".
 *  The object cache lives in the session's compile/ tree, keyed on the toolchain identity. */
mosura_status mosura_toolchain_open(mosura_session *s, const char *name, const mosura_options *opts, mosura_toolchain **out);
/** Compile a batch. `units`: key, source, flags(list). outputs: key, ok, adjudicated, object(bytes), log. */
mosura_status mosura_toolchain_compile(mosura_toolchain *tc, const mosura_table *units, mosura_table **outputs);
/** Recover the build flags of a function from the original's own bytes (shape → fact → flag):
 *  facts: fact, evidence; flags: the profile's flag list. */
mosura_status mosura_function_buildconfig(mosura_function *f, const mosura_options *opts, mosura_table **out);

/** Verify a compiled object against the original: symbolic relink at the original's address,
 *  lift both sides, align, attribute. Result: one `verdict` row (verdict, byte_verdict, sim,
 *  equal, orig_n, cand_n, primary_class) plus the `divergences` table (class, addr, oi, ci, orig,
 *  cand) reachable via `mosura_function_table(f, "divergences")` afterwards. */
mosura_status mosura_function_verify(mosura_function *f, mosura_view object, const mosura_options *opts, mosura_table **out);

/** One function end to end: passes → decompile → recover → tu → compile → verify. */
mosura_status mosura_function_recompile(mosura_function *f, mosura_toolchain *tc, const mosura_options *opts, mosura_table **out);

/** A round: every in-scope function of a program through `mosura_function_recompile`, results
 *  stored under rounds/<name>/ (verdicts, divergences, manifest, gates). `opts`: "round.scope"
 *  (user|all|list), "round.baseline=<name>", "round.exclude-foreign=1". */
mosura_status mosura_round_run(mosura_session *s, const char *name, mosura_program *p, mosura_toolchain *tc,
                               const mosura_options *opts, mosura_progress_fn progress, void *progress_user,
                               mosura_table **summary);
/** rounds: name, program_key, toolchain, build_id, when, exact, wgss, n. */
mosura_status mosura_rounds(mosura_session *s, mosura_table **out);
/** Compare two rounds over their common rows: the verdict transitions (ups, downs, unchanged),
 *  EXACT and WGSS deltas — today's war2-verdicts.sh. */
mosura_status mosura_round_compare(mosura_session *s, const char *a, const char *b, mosura_table **out);
/** The corpus gates (text gates over the TUs, verdict gates against a baseline): gate, outcome, detail. */
mosura_status mosura_round_gates(mosura_session *s, const char *round, const char *baseline, mosura_table **out);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MOSURA_H */
