//! The per-stage fingerprints (design §5.9, decision D7): a cache key uses the fingerprint of the
//! STAGE that produced a table, not the whole build id, so a printer edit does not re-run the
//! analysis. Computed here over the core's source tree, conservatively (P1 finding 5): the analysis
//! runs the decompiler (switch analyzer, the interface pass) and the sret shape reads the printer's
//! rendered slots, so `analysis` and `decompile` are one value = everything but the emit arms and
//! the recompile; `emit` = the emit arms, the printer, and the recompile modules the emit consults;
//! `recompile` = the whole recompile tree. Under-invalidation is the failure class
//! docs/measurement-rules.md exists for; correctness first, refinement identity-gated later.

use std::path::{Path, PathBuf};

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    if let Ok(rd) = std::fs::read_dir(dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.is_dir() {
                walk(&p, out);
            } else if p.extension().is_some_and(|x| x == "rs") {
                out.push(p);
            }
        }
    }
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let core_src = manifest.join("../mosura-core/src");
    println!("cargo:rerun-if-changed={}", core_src.display());
    println!("cargo:rerun-if-changed=build.rs");
    let mut files = Vec::new();
    walk(&core_src, &mut files);
    files.sort();
    let mut analysis = blake3::Hasher::new();
    let mut emit = blake3::Hasher::new();
    let mut recompile = blake3::Hasher::new();
    for f in &files {
        let rel = f.strip_prefix(&core_src).unwrap().to_string_lossy().replace('\\', "/");
        println!("cargo:rerun-if-changed={}", f.display());
        let bytes = std::fs::read(f).unwrap();
        let in_emit_arms = rel.starts_with("decompile/emit/");
        let in_recompile = rel.starts_with("recompile/");
        let emit_consults = rel == "decompile/printc.rs"
            || matches!(rel.as_str(), "recompile/recovery.rs" | "recompile/buildconfig.rs" | "recompile/insn.rs" | "recompile/watsched.rs");
        let mut feed = |h: &mut blake3::Hasher| {
            h.update(&(rel.len() as u32).to_le_bytes());
            h.update(rel.as_bytes());
            h.update(&(bytes.len() as u64).to_le_bytes());
            h.update(&bytes);
        };
        if !in_emit_arms && !in_recompile {
            feed(&mut analysis);
        }
        if in_emit_arms || emit_consults {
            feed(&mut emit);
        }
        if in_recompile {
            feed(&mut recompile);
        }
    }
    let a = analysis.finalize();
    let e = emit.finalize();
    let r = recompile.finalize();
    let arr = |h: &blake3::Hash| format!("{:?}", h.as_bytes());
    let out = format!(
        "/// blake3 over the core sources each stage depends on (generated by build.rs).\npub const FP_ANALYSIS: [u8; 32] = {};\npub const FP_DECOMPILE: [u8; 32] = {};\npub const FP_EMIT: [u8; 32] = {};\npub const FP_RECOMPILE: [u8; 32] = {};\npub const CORE_SOURCE_FILES: usize = {};\n",
        arr(&a), arr(&a), arr(&e), arr(&r), files.len()
    );
    std::fs::write(PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("fingerprints.rs"), out).unwrap();
}
