/*
 * mosura.h — the mosura C API. GENERATED by `cargo xtask header` from crates/mosura-capi;
 * do not edit by hand. Conventions (docs/product/architecture.md §4.5): every function returns a
 * mosura_status, details via mosura_last_error() (per thread); no panic crosses this boundary;
 * handles are opaque and released with mosura_release(); a mosura_view borrows (valid while the
 * producing handle lives), a mosura_bytes is owned (mosura_bytes_dispose); strings are UTF-8,
 * `const char *` parameters NUL-terminated; structs passed by pointer start with size + version.
 */

#ifndef MOSURA_H
#define MOSURA_H

#include <stddef.h>
#include <stdint.h>

/**
 * The API version this library implements; a client checks the major first.
 */
#define MOSURA_API_VERSION_MAJOR 0

#define MOSURA_API_VERSION_MINOR 1

/**
 * Column types (the `.tbl` codes).
 */
typedef enum {
  MOSURA_COL_U8 = 1,
  MOSURA_COL_U16,
  MOSURA_COL_U32,
  MOSURA_COL_U64,
  MOSURA_COL_I64,
  MOSURA_COL_F64,
  MOSURA_COL_BOOL,
  /**
   * UTF-8, in the blob
   */
  MOSURA_COL_STR,
  /**
   * raw bytes, in the blob
   */
  MOSURA_COL_BYTES,
  /**
   * variable-length list, in the blob
   */
  MOSURA_COL_LIST_U32,
  MOSURA_COL_LIST_U64,
} mosura_col_type;

/**
 * Renderings of a table.
 */
typedef enum {
  MOSURA_FMT_TEXT = 0,
  MOSURA_FMT_TSV,
  MOSURA_FMT_JSON,
} mosura_format;

/**
 * Diagnostic level of a log message.
 */
typedef enum {
  MOSURA_LOG_ERROR = 0,
  MOSURA_LOG_WARN,
  MOSURA_LOG_INFO,
  MOSURA_LOG_DEBUG,
} mosura_log_level;

/**
 * Every function returns one of these; details via `mosura_last_error()`.
 */
typedef enum {
  MOSURA_OK = 0,
  /**
   * NULL where a value is required, bad option key/value, bad handle kind, a released handle
   */
  MOSURA_ERR_INVALID_ARG,
  /**
   * no such function / table / operation / cache entry
   */
  MOSURA_ERR_NOT_FOUND,
  /**
   * session directory, input file, toolchain work dir
   */
  MOSURA_ERR_IO,
  /**
   * unreadable input, corrupt .tbl, unknown schema version
   */
  MOSURA_ERR_FORMAT,
  /**
   * no loader claims the file, language has no tables, op not built in
   */
  MOSURA_ERR_UNSUPPORTED,
  /**
   * the compiler could not be run (not: the source failed to compile)
   */
  MOSURA_ERR_TOOLCHAIN,
  /**
   * a progress callback returned non-zero
   */
  MOSURA_ERR_CANCELLED,
  /**
   * struct size/version mismatch, or a session written by an incompatible build
   */
  MOSURA_ERR_VERSION,
  /**
   * a panic was caught at the boundary; message = the panic text
   */
  MOSURA_ERR_INTERNAL,
} mosura_status;

/**
 * The library: spec registry, caches, log sink (opaque).
 */
typedef struct mosura_ctx mosura_ctx;

/**
 * One decompiled function (opaque).
 */
typedef struct mosura_function mosura_function;

/**
 * A SLEIGH language: tables + default context (opaque).
 */
typedef struct mosura_language mosura_language;

/**
 * A validated key/value option set (opaque).
 */
typedef struct mosura_options mosura_options;

/**
 * A loaded (and possibly analyzed) binary (opaque).
 */
typedef struct mosura_program mosura_program;

/**
 * A session store: a directory or memory (opaque).
 */
typedef struct mosura_session mosura_session;

/**
 * An immutable result table with a schema (opaque).
 */
typedef struct mosura_table mosura_table;

/**
 * Diagnostic sink. `topic` is the debug topic (`sparse-switch`, `analysis`, …) or "" for
 * untopiced messages; `msg` is NUL-terminated and `msg_len` its byte length. Replaces every
 * stderr print in the library.
 */
typedef void (*mosura_log_fn)(void *user,
                              mosura_log_level level,
                              const char *topic,
                              const char *msg,
                              size_t msg_len);

/**
 * Context configuration. Starts with `size` + `version`; use MOSURA_CTX_CONFIG_INIT. The library
 * reads only the fields `size` covers.
 */
typedef struct {
  /**
   * sizeof(mosura_ctx_config)
   */
  uint32_t size;
  /**
   * 1
   */
  uint32_t version;
  /**
   * Directories searched for spec data (`.ldefs`/`.sla`/`.pspec`/`.cspec`) BEFORE the embedded
   * set — the user's override folder (`mosura data export` writes one).
   */
  const char *const *spec_dirs;
  size_t spec_dirs_len;
  /**
   * Directories searched for FID databases (`.mfid[.gz]`, `.fidb`) before the embedded ones.
   */
  const char *const *fid_dirs;
  size_t fid_dirs_len;
  /**
   * Machine-level cache for frozen specs etc. NULL = none. (Accepted; unused in this version.)
   */
  const char *cache_dir;
  mosura_log_fn log;
  void *log_user;
  /**
   * Development aid: non-zero makes the boundary re-raise an internal panic (the process dies
   * with its backtrace) instead of catching it into MOSURA_ERR_INTERNAL. Release clients
   * leave it 0.
   */
  int abort_on_panic;
} mosura_ctx_config;

/**
 * Owned bytes. Dispose exactly once with `mosura_bytes_dispose`. Zero-initialized is a valid
 * empty value.
 */
typedef struct {
  uint8_t *ptr;
  size_t len;
  size_t cap;
} mosura_bytes;

/**
 * Borrowed, immutable bytes. Lifetime = the handle documented at the producing function.
 */
typedef struct {
  const uint8_t *ptr;
  size_t len;
} mosura_view;

/**
 * Progress callback for long operations. Return non-zero to cancel; the operation then fails
 * with MOSURA_ERR_CANCELLED and leaves no partial state in the session.
 */
typedef int (*mosura_progress_fn)(void *user, const char *stage, uint64_t done, uint64_t total);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Runtime ABI version, `(major << 16) | minor`.
 */
uint32_t mosura_abi_version(void);

/**
 * The human version string: the crate version plus the content-derived build id that also keys
 * the session store (e.g. `0.1.0 (0.0.0+3f2a9c1b7d4e)`). Static; never freed.
 */
const char *mosura_version(void);

/**
 * Release any handle. NULL is a no-op; a pointer that is not a live handle is refused (and
 * reported through `mosura_last_error`) rather than freed. A handle should outlive the handles
 * derived from it; the derived handles hold their own references, so releasing early is safe,
 * only surprising.
 */
void mosura_release(void *h);

/**
 * Create the library context. Thread-safe once created; everything derived from it is not,
 * unless stated. One configuration per process in this version: a second call with the same
 * override directories and panic policy answers the same context, a different one is
 * MOSURA_ERR_UNSUPPORTED.
 */
mosura_status mosura_ctx_new(const mosura_ctx_config *config, mosura_ctx **out);

/**
 * Write the EMBEDDED data into `dir` as the source files it was built from: `what` = "specs",
 * "fid" or "all". Existing files are kept unless `overwrite` is non-zero. Answers the files
 * written (`files`).
 */
mosura_status mosura_ctx_export_data(mosura_ctx *ctx,
                                     const char *dir,
                                     const char *what,
                                     int overwrite,
                                     mosura_table **out);

/**
 * What is in effect after overrides: name, source (`embedded` or the directory).
 */
mosura_status mosura_ctx_data_list(mosura_ctx *ctx, mosura_table **out);

/**
 * Decompile the function at `entry`. `opts` (NULL = none): decompile.global-scope,
 * decompile.proto-scope, knobs.off, and any emit.<axis> for the default rendering. The
 * decompile set is made now (or served); the handle then answers from it.
 */
mosura_status mosura_function_decompile(mosura_program *p,
                                        uint64_t entry,
                                        const mosura_options *opts,
                                        mosura_function **out);

/**
 * The C rendering under the handle's options (Ghidra's behaviour by default).
 */
mosura_status mosura_function_c(mosura_function *f, mosura_bytes *out);

/**
 * The C rendering under explicit emit choices (`emit.<axis>` keys) — the θ render.
 */
mosura_status mosura_function_render(mosura_function *f,
                                     const mosura_options *emit_choices,
                                     mosura_bytes *out);

/**
 * The IR: `stage` = "post" (after the pipeline; also "raw"), `format` TEXT = Ghidra `printRaw`
 * form. Other stages and formats are MOSURA_ERR_UNSUPPORTED in this version (no per-stage stop).
 */
mosura_status mosura_function_ir(mosura_function *f,
                                 const char *stage,
                                 mosura_format format,
                                 mosura_bytes *out);

/**
 * A function table by name: "prototype", "jumptables", "calls" (the decompile set); "report"
 * (the emit set's manifest row and notes). Others: MOSURA_ERR_NOT_FOUND / UNSUPPORTED.
 */
mosura_status mosura_function_table(mosura_function *f, const char *name, mosura_table **out);

/**
 * The standalone translation unit for the Watcom x86-32 toolchain: declarations, pragmas and
 * the recovered body (`function.emit`). `opts` (NULL = none): emit.<axis>, emit.arms-off,
 * knobs.off, decompile.*. The program's passes set is made when absent.
 */
mosura_status mosura_function_tu(mosura_function *f, const mosura_options *opts, mosura_bytes *out);

/**
 * The witness pass as a separate step. In this version recovery is part of `mosura_function_tu`
 * (MOSURA_ERR_UNSUPPORTED here).
 */
mosura_status mosura_function_recover(mosura_function *f,
                                      const mosura_options *_opts,
                                      mosura_table **_out);

/**
 * The emit axes (`EmitChoices::axes`): name, values, default, doc.
 */
mosura_status mosura_emit_axes(mosura_ctx *ctx, mosura_table **out);

/**
 * The emit arms (`Recovered::ARMS`): the names `emit.arms-off` accepts.
 */
mosura_status mosura_emit_arms(mosura_ctx *ctx, mosura_table **out);

/**
 * languages: id, processor, endian, size, variant, version, description, cspecs (comma list).
 */
mosura_status mosura_languages(mosura_ctx *ctx, mosura_table **out);

/**
 * Load a language by Ghidra id ("x86:LE:32:default"); MOSURA_ERR_NOT_FOUND when its tables
 * are not available.
 */
mosura_status mosura_language_open(mosura_ctx *ctx, const char *language_id, mosura_language **out);

/**
 * registers: name, space, offset, size.
 */
mosura_status mosura_language_registers(mosura_language *l, mosura_table **out);

/**
 * Disassemble raw bytes. `ctx_regs` (NULL = the `.pspec` defaults) is an option set whose `ctx`
 * key holds the context register settings ("addrsize=1;opsize=1").
 * instructions: addr, len, bytes, mnemonic, operands, flow columns (empty for a raw decode).
 */
mosura_status mosura_disassemble(mosura_language *l,
                                 mosura_view bytes,
                                 uint64_t base,
                                 const mosura_options *ctx_regs,
                                 mosura_table **out);

/**
 * Lift raw bytes to raw p-code. pcode: addr, seq, opcode, mnemonic, output (space, offset,
 * size), inputs (spaces, offsets, sizes), text (the golden form).
 */
mosura_status mosura_lift(mosura_language *l,
                          mosura_view bytes,
                          uint64_t base,
                          const mosura_options *ctx_regs,
                          mosura_table **out);

/**
 * Execute the p-code of a byte range with an initial state. Not in this version
 * (MOSURA_ERR_UNSUPPORTED).
 */
mosura_status mosura_emulate(mosura_language *l,
                             mosura_view _bytes,
                             uint64_t _base,
                             const mosura_options *_initial_state,
                             mosura_table **_out);

/**
 * FID fingerprints for a byte range. Not in this version (MOSURA_ERR_UNSUPPORTED).
 */
mosura_status mosura_fingerprint(mosura_language *l,
                                 mosura_view _bytes,
                                 uint64_t _base,
                                 mosura_table **_out);

/**
 * Free a buffer handed out as `mosura_bytes`; NULL or an empty value is a no-op, and the struct
 * is zeroed so a second dispose is harmless.
 */
void mosura_bytes_dispose(mosura_bytes *b);

/**
 * The operation registry as a table: name, tier, since, cache, params, result, doc. `include_dev`
 * adds the dev tier (none in a release build).
 */
mosura_status mosura_ops(mosura_ctx *ctx, int include_dev, mosura_table **out);

/**
 * The schema of a named table type, as a table of columns (col, type, hint).
 */
mosura_status mosura_schema(mosura_ctx *ctx, const char *table_name, mosura_table **out);

/**
 * Invoke any operation by name. `params` (NULL = none) carries the op's parameters as option
 * keys ("input", "entry", "format", … are ordinary keys); the session config supplies defaults
 * for the keys the op accepts. The result is a table; text results are a one-row `text` table.
 * Pure operations are served from the session store when their key is present.
 */
mosura_status mosura_call(mosura_session *s,
                          const char *op,
                          const mosura_options *params,
                          mosura_progress_fn progress,
                          void *progress_user,
                          mosura_table **out);

/**
 * An empty option set.
 */
mosura_status mosura_options_new(mosura_ctx *ctx, mosura_options **out);

mosura_status mosura_options_clone(const mosura_options *src, mosura_options **out);

/**
 * Set a key. Unknown keys and ill-typed values are MOSURA_ERR_INVALID_ARG with the registry's
 * doc line in the error message. Keys are dotted lower-case ("load.loader", "emit.return-width").
 */
mosura_status mosura_options_set(mosura_options *o, const char *key, const char *value);

mosura_status mosura_options_unset(mosura_options *o, const char *key);

/**
 * The effective value (explicit or default). The view is valid until the next mutation of `o`.
 */
mosura_status mosura_options_get(const mosura_options *o, const char *key, mosura_view *out);

/**
 * Canonical string of the RESULT-affecting subset — the option digest used in cache keys.
 */
mosura_status mosura_options_tag(const mosura_options *o, mosura_bytes *out);

/**
 * Parse "key=value;key=value" (a bare key sets a Bool to true).
 */
mosura_status mosura_options_assign(mosura_options *o, const char *spec);

/**
 * The registry: one row per key — key, type, default, doc, since, affects.
 */
mosura_status mosura_options_registry(mosura_ctx *ctx, mosura_table **out);

/**
 * Everything mosura can say about a file without analysing it: one row per fact (key, value,
 * evidence). Runs on a private in-memory session.
 */
mosura_status mosura_identify(mosura_ctx *ctx, mosura_view bytes_in, mosura_table **out);

/**
 * Load an input of the session (`input` = a label or digest; NULL = the only one) into a
 * Program. `load_opts` (NULL = defaults): load.loader, load.language, load.base,
 * load.cspec-x86-32, analysis.disable, knobs.off. Served from the store when the key exists.
 */
mosura_status mosura_program_open(mosura_session *s,
                                  const char *input,
                                  const mosura_options *load_opts,
                                  mosura_program **out);

/**
 * Run auto-analysis to convergence (`opts`, NULL = none: analysis.disable, knobs.off — added to
 * the program's options). The program's key becomes the analyzed set's; a cached one returns
 * immediately.
 */
mosura_status mosura_program_analyze(mosura_program *p,
                                     const mosura_options *opts,
                                     mosura_progress_fn progress,
                                     void *progress_user);

/**
 * Whole-program passes that feed emission (the survey's pass 1, promoted): prototype recovery,
 * tail-return marks, parameter-order evidence, global widths. `opts` (NULL = none): knobs.off,
 * decompile.global-scope, decompile.proto-scope (the survey used `standalone`).
 */
mosura_status mosura_program_passes(mosura_program *p,
                                    const mosura_options *opts,
                                    mosura_progress_fn progress,
                                    void *progress_user);

/**
 * A program table by name ("functions", "symbols", "references", "blocks", "listing", …, and
 * the virtual "snapshot"); an empty name lists the tables. Unknown name: MOSURA_ERR_NOT_FOUND.
 */
mosura_status mosura_program_table(mosura_program *p, const char *name, mosura_table **out);

/**
 * Bytes of the loaded image at `addr`. The view is valid until the next `mosura_program_read`
 * on this handle (or its release). An unloaded address is MOSURA_ERR_NOT_FOUND.
 */
mosura_status mosura_program_read(mosura_program *p, uint64_t addr, size_t len, mosura_view *out);

/**
 * Disassembly of a range from the listing (decoded on demand; text is never stored).
 */
mosura_status mosura_program_disassemble(mosura_program *p,
                                         uint64_t addr,
                                         size_t len,
                                         mosura_table **out);

/**
 * The session's stable key for this program (64 hex; the directory under program/).
 */
mosura_status mosura_program_key(mosura_program *p, mosura_bytes *key_hex);

/**
 * User annotations. Not in this version (MOSURA_ERR_UNSUPPORTED).
 */
mosura_status mosura_program_annotate(mosura_program *p,
                                      const char *_kind,
                                      uint64_t _addr,
                                      const char *_payload);

mosura_status mosura_program_unannotate(mosura_program *p, const char *_kind, uint64_t _addr);

/**
 * The Snapshot v1 text (the analysis golden format) — the TEXT rendering of the program's tables.
 */
mosura_status mosura_program_snapshot(mosura_program *p, mosura_bytes *out);

/**
 * Open or create a session. `dir == NULL` is an in-memory session (nothing persists). The
 * session's own config table supplies option defaults for every operation run in it; `config`
 * (NULL = none) is written into it.
 */
mosura_status mosura_session_open(mosura_ctx *ctx,
                                  const char *dir,
                                  const mosura_options *config,
                                  mosura_session **out);

/**
 * Add an input binary (content-addressed). `label` (NULL = "input") names it for the commands
 * and is also the file name the container dispatch sees — pass the file's name (with its
 * extension) for `.com` detection, or select the loader with `load.loader`. Re-adding identical
 * bytes is a no-op answering the same digest. `digest_hex` (NULL = not wanted) receives the
 * 64-hex blake3 digest.
 */
mosura_status mosura_session_add_input(mosura_session *s,
                                       mosura_view bytes_in,
                                       const char *label,
                                       mosura_bytes *digest_hex);

/**
 * inputs: label, digest, size, filename, added.
 */
mosura_status mosura_session_inputs(mosura_session *s, mosura_table **out);

/**
 * Provenance of a stored table set (a program or function key, 64 hex): kind, name, value rows
 * — inputs, options tag, stage fingerprint, build id, creation time, tables.
 */
mosura_status mosura_session_explain(mosura_session *s, const char *key, mosura_table **out);

/**
 * The stored table sets (kind, key, tables, bytes). This version lists only: `dry_run` must be
 * non-zero (removal is MOSURA_ERR_UNSUPPORTED until rounds exist to define reachability).
 */
mosura_status mosura_session_gc(mosura_session *s, int dry_run, mosura_table **out);

/**
 * The message for the last non-OK status on THIS thread. Valid until the next mosura call on
 * the thread. Never NULL (empty when there is none).
 */
const char *mosura_last_error(void);

/**
 * Schema identity: name (e.g. "functions"), version, column count.
 */
mosura_status mosura_table_schema(const mosura_table *t,
                                  mosura_view *name,
                                  uint32_t *version,
                                  uint32_t *ncols);

/**
 * A column's name and type.
 */
mosura_status mosura_table_column_info(const mosura_table *t,
                                       uint32_t col,
                                       mosura_view *name,
                                       mosura_col_type *ty);

/**
 * Column index by name, or MOSURA_ERR_NOT_FOUND — the way a client survives appended columns.
 */
mosura_status mosura_table_column_index(const mosura_table *t, const char *name, uint32_t *col);

/**
 * The row count (0 and a recorded error for a bad handle).
 */
uint64_t mosura_table_rows(const mosura_table *t);

/**
 * A U64 cell (any unsigned integer column widens: U8, U16, U32, U64).
 */
mosura_status mosura_table_u64(const mosura_table *t, uint64_t row, uint32_t col, uint64_t *out);

/**
 * An I64 cell.
 */
mosura_status mosura_table_i64(const mosura_table *t, uint64_t row, uint32_t col, int64_t *out);

/**
 * An F64 cell.
 */
mosura_status mosura_table_f64(const mosura_table *t, uint64_t row, uint32_t col, double *out);

/**
 * A Bool cell (0/1).
 */
mosura_status mosura_table_bool(const mosura_table *t, uint64_t row, uint32_t col, int *out);

/**
 * A Str cell (UTF-8, not NUL-terminated; the view is valid for the table's life).
 */
mosura_status mosura_table_str(const mosura_table *t, uint64_t row, uint32_t col, mosura_view *out);

/**
 * A Bytes cell.
 */
mosura_status mosura_table_bytes(const mosura_table *t,
                                 uint64_t row,
                                 uint32_t col,
                                 mosura_view *out);

/**
 * A list cell as a view over `count` little-endian elements of the column's element width
 * (4 for LIST_U32, 8 for LIST_U64).
 */
mosura_status mosura_table_list(const mosura_table *t,
                                uint64_t row,
                                uint32_t col,
                                mosura_view *out,
                                uint64_t *count);

/**
 * Bulk, zero-copy access to a fixed-width column: `out` spans all rows, `stride` is the row size
 * in bytes (row-major storage; a client builds a strided array view).
 */
mosura_status mosura_table_column(const mosura_table *t,
                                  uint32_t col,
                                  mosura_view *out,
                                  uint32_t *stride);

/**
 * Binary search on a sorted key column (a table sorted on column 0 says so in its flags; other
 * columns are scanned). MOSURA_ERR_NOT_FOUND when no row carries `key`.
 */
mosura_status mosura_table_find(const mosura_table *t, uint32_t col, uint64_t key, uint64_t *row);

/**
 * Render the whole table: TEXT (the human form; a `text` table prints bare), TSV (header row),
 * JSON (an array of objects). UTF-8, not NUL-terminated.
 */
mosura_status mosura_table_render(const mosura_table *t, mosura_format format, mosura_bytes *out);

/**
 * The flat `.tbl` image — what the session store writes.
 */
mosura_status mosura_table_serialize(const mosura_table *t, mosura_bytes *out);

/**
 * Open a `.tbl` image. The bytes are copied in this version (`borrow` is accepted and treated as
 * copy); the digest is verified; a schema name the library knows with another version is
 * refused (MOSURA_ERR_FORMAT), an unknown name is served with the file's own schema.
 */
mosura_status mosura_table_open(mosura_ctx *ctx,
                                mosura_view image,
                                int _borrow,
                                mosura_table **out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MOSURA_H */

/** Initializer for mosura_ctx_config: the current struct size, version 1, everything else off. */
#define MOSURA_CTX_CONFIG_INIT { (uint32_t)sizeof(mosura_ctx_config), 1, NULL, 0, NULL, 0, NULL, NULL, NULL, 0 }
